# Generated by Django 3.0.7 on 2020-07-01 02:20

import board.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rentGu', models.CharField(max_length=20)),
                ('rentDong', models.CharField(max_length=20)),
                ('stationName', models.CharField(max_length=100)),
                ('stationNum', models.IntegerField(default=0)),
                ('stationValue', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Recede',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recedeTime', models.DateTimeField()),
                ('restationNum', models.IntegerField(default=0)),
                ('restationName', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['recedeTime'],
            },
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rentTime', models.DateTimeField()),
                ('stationNum', models.IntegerField(default=0)),
                ('stationName', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['rentTime'],
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to=board.models.notices_image_path)),
                ('upload', models.FileField(blank=True, upload_to=board.models.notices_image_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.Notice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
